#!/usr/bin/env python3
"""Aggregate oracle Macro FER (birds within species, then species) into results/oracle_fer.md."""
import json, statistics as st
from pathlib import Path

root = Path(__file__).resolve().parents[1] / "results"
species = {"canary": "Canary", "zf": "Zebra finch", "bf": "Bengalese finch"}
data = {s: [json.loads(p.read_text())["rows"] for p in sorted((root / "oracle" / s).glob("*.json"))] for s in species}
mean = lambda s, i, k: 100 * st.mean(rows[i][k] for rows in data[s])
lines = ["# Oracle Macro FER by output resolution", "",
         "Probe data selection and 1 ms scoring; birds averaged within species, then species. "
         "`majority`: each bin predicts its majority label (as R1 asked). `macro_optimal`: each bin predicts the "
         "label maximizing class frames in bin / class frames overall, the lowest Macro FER reachable on that grid. "
         "Generated by `scripts/oracle_table.py`.", ""]
for oracle in ("majority", "macro_optimal"):
  lines += ["", f"## {oracle}", "",
            "| Bin | " + " | ".join(f"{v} FER" for v in species.values()) + " | Mean (3 spp.) | Mean (zf+bf) | Parsing (3 spp.) | Identity (3 spp.) |",
            "|---" * 8 + "|"]
  for i, row in enumerate(data["zf"][0]):
    if row["oracle"] != oracle:
        continue
    ms = row["bin_ms"]
    per = {s: mean(s, i, "macro_fer") for s in species}
    lines.append(f"| {ms:g} ms | " + " | ".join(f"{per[s]:.2f}" for s in species)
                 + f" | {st.mean(per.values()):.2f} | {st.mean([per['zf'], per['bf']]):.2f}"
                 + f" | {st.mean(mean(s, i, 'macro_parsing_error') for s in species):.2f}"
                 + f" | {st.mean(mean(s, i, 'macro_identity_error') for s in species):.2f} |")
lines += ["", f"Birds: " + ", ".join(f"{species[s]} {len(v)}" for s, v in data.items())]
(root / "oracle_fer.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
